spring.application.name=todoAPI
spring.datasource.url=jdbc:mysql://localhost:3306/todo?createDatabaseIfNotExist=TRUE
spring.datasource.username=pw
spring.datasource.password=M3lhormateria!
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.locations=classpath:db/migration/mysql
spring.flyway.enabled=true


