# Conexão via variáveis de ambiente com valores de fallback (ou obrigatórias)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
api.security.token.secret=${TOKEM_SECRET}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.web.error.include-stacktrace=never
